spring:
  application:
    name: api
  main:
    banner-mode: off

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health