name: "Setup Java and Gradle"
description: "Sets up JDK 24 with Gradle caching"
runs:
    using: "composite"
    steps:
        - name: Set up JDK 24
          uses: actions/setup-java@v4
          with:
              java-version: "24"
              distribution: "temurin"
              cache: gradle
              cache-dependency-path: backend/**/*.gradle*
