spring:
  application:
    name: auth
  main:
    banner-mode: off

server:
  port: 9000
  servlet:
    context-path: ""
  error:
    whitelabel:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health