spring:
  config:
    import: file:.local.env[.properties]

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  exposed:
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console