name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  shared-tests:
    name: "Test Shared Module"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: backend/**/*.gradle*

      - name: Test shared module
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew :shared:test --no-daemon --parallel

  api-tests:
    name: "Test API Module"
    runs-on: ubuntu-latest
    needs: shared-tests # ensure shared-tests completes first
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: backend/**/*.gradle*

      - name: Test API module
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew :api:test --no-daemon --parallel

  auth-tests:
    name: "Test Auth Module"
    runs-on: ubuntu-latest
    needs: shared-tests # ensure shared-tests completes first
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: backend/**/*.gradle*

      - name: Test Auth module
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew :auth:test --no-daemon --parallel

  build:
    name: "Build and Upload API & Auth JARs"
    runs-on: ubuntu-latest
    needs:
      - api-tests
      - auth-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle
          cache-dependency-path: backend/**/*.gradle*

      - name: Build API and Auth JARs
        working-directory: ./backend
        run: |
          chmod +x ./gradlew
          ./gradlew :api:bootJar :auth:bootJar --no-daemon --parallel

      - name: Upload API JAR
        uses: actions/upload-artifact@v4
        with:
          name: api-jar
          path: backend/api/build/libs/*.jar

      - name: Upload Auth JAR
        uses: actions/upload-artifact@v4
        with:
          name: auth-jar
          path: backend/auth/build/libs/*.jar